<ul class="lifestream">
<?php foreach ($this->entries as $entry):?>
    <li class="<?= $entry->code ?>">
        <a href="<?= $entry->url ?>"><?= $entry->title ?></a> 
        <?php if ($entry->display_content):?>
        <p><?= $entry->content; ?></p>
        <?php endif;?>
        <span class="since"><?= $this->date($entry->content_created_at)->get(Zend_Date::RFC_850) ?></span>
    </li>
<?php endforeach;?>
</ul>

<?= $this->entries ?>