<ul class="lifestream">
<?php foreach ($this->entries as $entry):?>
    <li class="<?= $entry->code ?>">
        <a href="<?= $entry->url ?>"><?= $entry->title ?></a> 
        <?php if ($entry->display_content):?>
        <p><?= $entry->content; ?></p>
        <?php endif;?>
        <?php $date = $this->date($entry->content_created_at)?>
        <span class="since" title="<?= $date->get(Zend_Date::RFC_850)?>">
            <a href="<?= $this->url(array('id' => $entry->id, 'controller' => 'streams', 'action' => 'show'))?>"><?= $this->humanTimeSince($date)?> ago</a>
        </span>
    </li>
<?php endforeach;?>
</ul>