<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="http://yui.yahooapis.com/2.5.1/build/reset-fonts-grids/reset-fonts-grids.css" type="text/css">
    <link href="/stylesheets/lifestream.css" media="screen" rel="stylesheet" type="text/css" />
    <title><?= $this->title ?> - Lifestream</title>
</head>
<body>
<div id="doc3" class="yui-t7">
   <div id="hd"><h1>My Lifestream</h1></div>
   <div id="bd">
    <div class="yui-ge">
    <div class="yui-u first">
        <?= $this->layout()->content; ?>
    </div>
    <div class="yui-u">
        <?= $this->myStreams(); ?>
    </div>
</div>

</div>
   <div id="ft">Footer is here.</div>
</div>
</body>
</html>
